Initial application and deployment
Informasjonsforvaltning/data-service-catalog pull request #2
Opened 2024-11-08 09:54 UTC by torleifg

closes #1

2024-11-08 12:52 UTC, NilsOveTen reviewed
du kan jo legge til en test som sjekker at endepunktene for ping og/eller ready fungerer

2024-11-08 12:57 UTC, NilsOveTen reviewed
og siden du legger til SecurityConfig så kan du opprette en et POST-endepunkt, det trenger ikke noe innhold ut over å svare not-implemented elns, og sjekke at JWT-konfigurasjonen fungerer

2024-11-08 13:08 UTC, NilsOveTen commented on deploy/base/data-service-catalog-deployment.yaml
> +              memory: "350Mi"
@valosnah hva burde vi ta med her?

2024-11-11 08:28 UTC, valosnah commented on deploy/base/data-service-catalog-deployment.yaml
> +              memory: "350Mi"
Request: cpu og memory
Limit: memory, og den skal være lik request.

Mengden kommer selvsagt litt an på hvor tungkjørt appen er. Eksempelvis dataset-catalog:
```
          resources:
            requests:
              memory: "750Mi"
              cpu: "20m"
            limits:
              memory: "750Mi"
```

2024-11-11 08:30 UTC, valosnah commented on deploy/staging/kustomization.yaml
> +
Husk å legge til
`- ingress.yaml`
hvis du legger på ingress som Nils Ove foreslår.

2024-11-11 08:31 UTC, valosnah commented on deploy/staging/kustomization.yaml
> +
(Fordrer selvsagt at du legger ingress-filen i denne mappen og kaller den ingress.yaml, som er standarden vi forsøker å følge)

2024-11-11 08:33 UTC, valosnah requested changes
Se kommentarer

2024-11-11 09:21 UTC, valosnah commented on deploy/base/kustomization.yaml
> +    newName: eu.gcr.io/digdir-fdk-infra/data-service-catalog
Kan du også endre denne linjen til
`newName: ghcr.io/informasjonsforvaltning/data-service-catalog`

2024-11-12 07:20 UTC, NilsOveTen commented on deploy/staging/ingress.yaml
> +  name: data-service-catalog
@valosnah nå kopierte jeg bare limit-input fra llm-tjenesten, noe der vi bør flikke på?

2024-11-12 11:04 UTC, valosnah commented on deploy/staging/ingress.yaml
> +  name: data-service-catalog
limit-rp~s~: '2'
multiplier: '2'

2024-11-12 14:57 UTC, valosnah approved these changes

2024-11-13 06:36 UTC, NilsOveTen approved these changes
https://data-service-catalog.api.staging.fellesdatakatalog.digdir.no/swagger-ui/index.html

Den fungerer ikke pga streng rate-limit, så greit å enten øke rate-limit til det fungerer eller bare droppe swagger-ui

2024-11-15 11:07 UTC, merged