Initial data service api implementation and test
Informasjonsforvaltning/data-service-catalog pull request #4
Opened 2024-11-18 10:55 UTC by torleifg

2024-11-18 11:21 UTC, NilsOveTen reviewed
@valosnah har gjort endringer på actions-workflow, for å gå over til å bruke github-registry, så du må fikse din deploy-workflow her for å matche de endringene

2024-11-18 11:21 UTC, NilsOveTen commented on src/main/kotlin/no/fdk/dataservicecatalog/controller/CatalogController.kt
> +@RequestMapping("/catalogs", produces = [N3, TURTLE, RDF_XML, RDF_JSON, JSON_LD, TRIX, TRIG, N_QUADS, N_TRIPLES])
Siden disse serialiseringene ikke blir 1 til 1 lik utgavene i JSON og endepunktene skal være helt åpne så tror jeg vi bør gå bort fra at de har samme path. Kanskje prefikse med /published

dvs:
```suggestion
@RequestMapping("/published/catalogs", produces = [N3, TURTLE, RDF_XML, RDF_JSON, JSON_LD, TRIX, TRIG, N_QUADS, N_TRIPLES])
```

2024-11-18 11:21 UTC, NilsOveTen commented on src/main/kotlin/no/fdk/dataservicecatalog/controller/CatalogController.kt
> +@RequestMapping("/catalogs", produces = [N3, TURTLE, RDF_XML, RDF_JSON, JSON_LD, TRIX, TRIG, N_QUADS, N_TRIPLES])
men det kommer til å ha litt andre følger. Tenker i tillegg at det vi går for i dette apiet er varianten vi endrer de andre registreringsbackendene til å følge.

mao bør nok ta dette opp med resten av teamet

2024-11-18 11:21 UTC, NilsOveTen commented on src/main/kotlin/no/fdk/dataservicecatalog/controller/DataServiceController.kt
> +        @PathVariable catalogId: String, @Valid @RequestBody registerDataServiceCommand: RegisterDataServiceCommand
Tviler på at du trenger seperate DTO for create og find
```suggestion
    fun findDataServicesByCatalogId(@PathVariable catalogId: String): ResponseEntity<List<DataService>> {
        return ResponseEntity.status(HttpStatus.NOT_IMPLEMENTED).build()
    }

    @GetMapping("{catalogId}/data-services/{dataServiceId}", produces = [MediaType.APPLICATION_JSON_VALUE])
    fun findDataServiceByCatalogIdAndDataServiceId(
        @PathVariable catalogId: String, @PathVariable dataServiceId: String
    ): ResponseEntity<DataService> {
        return ResponseEntity.status(HttpStatus.NOT_IMPLEMENTED).build()
    }

    @PostMapping("{catalogId}/data-services", consumes = [MediaType.APPLICATION_JSON_VALUE])
    fun registerDataServiceByCatalogId(
        @PathVariable catalogId: String, @Valid @RequestBody dataService: DataService
```

2024-11-18 11:23 UTC, NilsOveTen commented
> Men det er kanskje fleire/nye endpunkter som skal med i ny applikasjon, jf. service-catalog?

service-catalog er backend for to skjemaer, så du kommer til å trenge ca halvparten av mengden endepunkt den har

2024-11-18 11:46 UTC, NilsOveTen commented on src/main/kotlin/no/fdk/dataservicecatalog/controller/CatalogController.kt
> +@RequestMapping("/catalogs", produces = [N3, TURTLE, RDF_XML, RDF_JSON, JSON_LD, TRIX, TRIG, N_QUADS, N_TRIPLES])
vi har visst tatt opp dette tidligere i forbindelse med `service-catalog`, stryk denne kommentaren. Det er json endepunktene som skal ha /internal som prefix

2024-11-18 11:53 UTC, NilsOveTen requested changes

2024-11-18 11:53 UTC, NilsOveTen commented on src/main/kotlin/no/fdk/dataservicecatalog/controller/DataServiceController.kt
> +@RequestMapping("/catalogs")
JSON-endepunktene er kun for intern trafikk knyttet til frontend-skjemaet, det skal prefikses med /internal
```suggestion
@RequestMapping("/internal/catalogs")
```

2024-11-18 11:53 UTC, NilsOveTen commented on src/main/kotlin/no/fdk/dataservicecatalog/controller/CatalogController.kt
> +class CatalogController {
`Catalog` viser ikke hva som er forskjellem mellom denne og /catalogs-endepunktet til DataServiceController, du kan feks endre det til `RDFController` eller `PublishedController`. Ser vi har brukt RDFController i service-catalog
```suggestion
class RDFController {
```

2024-11-19 11:12 UTC, torleifg commented
closes #3

2024-11-19 12:03 UTC, NilsOveTen commented on src/main/kotlin/no/fdk/dataservicecatalog/controller/RDFController.kt
bør i tillegg ha findDataServiceById her i RDFController

2024-11-19 12:14 UTC, NilsOveTen commented on src/main/kotlin/no/fdk/dataservicecatalog/domain/DataService.kt
> +    val endpointUrl: String? = null,
er ikke `@field:NotBlank` + `: String? = null` litt selvmotsigende?

2024-11-19 12:32 UTC, torleifg commented on src/main/kotlin/no/fdk/dataservicecatalog/domain/DataService.kt
> +    val endpointUrl: String? = null,
Ja, men det er Kotlin problematikk som skal finne ein meir elegant løysing på etterkvart.

2024-11-19 14:07 UTC, merged